update

diff --git a/git_templates/hooks/pre-commit-abort-regex b/git_templates/hooks/pre-commit-abort-regex
--- a/git_templates/hooks/pre-commit-abort-regex
+++ b/git_templates/hooks/pre-commit-abort-regex
@@ -1,13 +1,19 @@
 #!/bin/bash
 
 git_root_dir="$(git rev-parse --show-toplevel)"
-abort_regex="^# Copyright ([0-9]{4}-)?(?!$(date '+%Y'))([0-9]{4}),.*$"
+abort_regex=(
+  "^# Copyright ([0-9]{4}-)?(?!$(date '+%Y'))([0-9]{4}),.*$" \
+  "Sony Corporation" \
+  "xTakashi.Honda@jp.sony.com" \
+)
 
 for FILE in $(git diff-index --name-status HEAD -- | cut -c3-); do
-  if grep -P "$abort_regex" "$git_root_dir/$FILE"; then
-    echo "Matched abort_regex. Please check the file."
-    echo "Regex: $abort_regex"
-    echo "File: $FILE"
-    exit 1
-  fi
+  for ((i = 0; i < ${#abort_regex[@]}; i++)) {
+    if grep -P "${abort_regex[i]}" "$git_root_dir/$FILE"; then
+      echo "Matched abort_regex. Please check the file."
+      echo "Regex: ${abort_regex[i]}"
+      echo "File: $FILE"
+      exit 1
+    fi
+  }
 done
